### ISSUE TITLE
GetDescriptionOfDateInformation doesn't handle dates less than a year apart

### ISSUE THREAD

**Issue by msackton** [tsackton/taelgar#10]
The getDescriptionOfDateInformation takes a date info (with a start date, end date, and age) and outputs one of the following strings:
* pagePast
* pagePastWithStart
* pageCurrent

However, the age is in years, so if you have someone who is (a) dead and (b) has birth/death dates in the same year, it incorrectly selects the pagePast rather than pagePastWithCurrent.

I have not checked to see if Python has the same bug.

**Comment by msackton** [comment]
This can be observed in the regnal dates for Charlotte II of Sembara

**Comment by tsackton** [comment]
Python had same bug, although now fixed. Source was:
```
        if date_info.get('isAlive'):
            format_str = page_display_data.get('pageCurrent', "")
        elif date_info.get('age'):
            format_str = page_display_data.get('pagePastWithStart', "")
        elif date_info.get('endDate'):
            format_str = page_display_data.get('pagePast', "")
        else:
            return ""
```

Where if age is 0, that is falsey, and so elif date_info.get('age') doesn't happen.
