### ISSUE TITLE
Allow displayDefaults overrides in whereabouts, allow 'slices' in <loc>

### ISSUE THREAD

**Issue by tsackton** [tsackton/taelgar#19]
I was playing around with setting the location of certain people to an organization, e.g., set the location of Ander Charmheart to Charmheart Trading Caravan. Or, set the location of Delwath to Dunmar Fellowship. 

This has a lot of advantages to save copying and pasting when people are traveling together, but has kind of a nitpicky display issue. First, and I think most importantly, the whereabouts lines are getting quite long, and if Delwath is in the Dunmar Fellowship which is in Vindristjarna which is traveling to Uzguhkar, Xurkhaz, it starts to be a lot of text. You might not need to display, for instance, that Delwath is with the Dunmar Fellowship. So it might be nice to have the option to take a location slice, just display elements 2, 3, and 4, for example. 

However, for this to be satisfying, you'd really like to be able to set this just for a specific whereabouts. E.g., for Delwath you might have the pre-campaign stuff, then { type: away, location: traveling with the Dunmar Fellowship }, with the solo quest in the middle. But you probably only want to skip the first loc for the specific "with the Dunmar fellowship" line, otherwise you get "Originally from: Central Highlands Region" instead of "Ainumarye, Central Highlands Region."

There are also times where you might use this in an informal way, e.g. to track the shared movements of various NPC parties, where it isn't desired behavior to show the NPC party name. 

Still thinking a bit about other ideas but just getting notes on the page.

**Comment by msackton** [comment]
Proposal is to allow a “format” option on a whereabouts line. This will be able to be of the form:

[number]RrIiFfOoPpLl

where 
Number is the max depth for that whereabouts line. 

R or r means only or exclude typeOf: region
I or i means only or exclude items
F or f means only first or exclude first
O or o means only or exclude organizations
P or p means only or exclude people
L or l means only or exclude locations (places)

so for example format: “3pi” would so 3 deep, excluding people or items. 

Note this can also be applied in a format position of a location string (ie <current:3pi>) but if the specific current whereabout has a format that wins over the general format.

**Comment by tsackton** [comment]
Keeping this open as a placeholder for possibly addressing slices in the future.

**Comment by msackton** [comment]
Slices are now supported in #24  - format: "2-4r" is the 2nd - 4th pieces, excluding regions.

"2-" is unbounded max, 2 min
"2" is max of 2

Note the format numbers must be first part of the format string
