### ISSUE TITLE
Issues/questions: LocationManager

### ISSUE THREAD

**Issue by tsackton** [tsackton/taelgar#23]
1. The code:
```
if (locationPiece == "Taelgar") return ""
```
Currently just deletes the word Taelgar from location strings if it is the first capitalized word of the string, unless the string has a comma; and also terminates location chains at the level below Taelgar. This is probably not the desired behavior. Need to think about how to fix it.

2. The linking stuff is inconsistent depending on whether there is a comma, for reasons I don't yet fully understand. E.g. "floating, in the ~Eastern Skies~" generates "[[floating]], in the ~Eastern Skies~" while "floating in the ~Eastern Skies~" generates "floating in the [[~Eastern Skies~]]". I assume this is because of how strings get split, in the first you have "floating; in the Eastern Skies" in the second you have "floating in the; Eastern Skies"? Probably there is a way to neaten this up a bit but need to think about exactly how or if it is worthwhile. E.g., maybe we just treat: "sleeping, elder tree in Rostare" as a data entry error which should be "sleeping in the elder tree in Rostare".

**Comment by msackton** [comment]
code_cleanup fixes this by

(a) For the string Taelgar, we delete it unless the "depth" of the Taelgar string is 1 and regions are allowed. 
(b) We have removed a bunch of special handling around commas, and now "something something Place" and "something, something, Place" are treated the same. Anything that depended on "something, Place1, Place2" will no longer work
